twist_mux:
  ros__parameters:
    topics:
      navigation:
        topic: cmd_vel_nav
        timeout: 2.0
        priority: 10
      joystick:
        topic: cmd_vel_manual
        timeout: 2.0
        priority: 1
    use_stamped: false
