twist_mux:
  ros__parameters:
    topics:
      aruco_mission:
        topic: cmd_vel_aruco
        timeout: 0.5
        priority: 10
      joystick:
        topic: cmd_vel_manual
        timeout: 2.0
        priority: 1
    use_stamped: false
